### ISSUE TITLE
Where did the project go? 

### ISSUE THREAD

**Issue by davelab6** [MoonLightDE/MoonLightDE#35]
I am curious why this project stopped being developed..?

**Comment by azubieta** [comment]
Hello Dave: 
We stop due, leak of man power. I get really bussy in my current job so I had to stop it, and no one has show up to take it again. 

Best 

----- Mensaje original -----

De: "Dave Crossland" <notifications@github.com> 
Para: "MoonLightDE/MoonLightDE" <MoonLightDE@noreply.github.com> 
Enviados: Jueves, 31 de Marzo 2016 23:49:37 
Asunto: [MASSMAIL][MoonLightDE/MoonLightDE] Where did the project go? (#35) 



I am curious why this project stopped being developed..? 

— 
You are receiving this because you are subscribed to this thread. 
Reply to this email directly or view it on GitHub 




-- 
Eng. Alexis López Zubieta 
University of Informatics Sciences, Cuba

**Comment by davelab6** [comment]
I understand :) Thanks for the note :)
